//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UsersDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public int CarID { get; set; }
        public string Email { get; set; }
        public string Company { get; set; }
        public string ModelNo { get; set; }
        public string RegistrationNo { get; set; }
        public string ShowroomAddress { get; set; }
        public Nullable<int> CurrentMileage { get; set; }
        public Nullable<int> NextOil { get; set; }
        public Nullable<int> NextTyre { get; set; }
        public Nullable<int> NextFuel { get; set; }
        public Nullable<int> NextTuning { get; set; }
        public Nullable<int> NextFilter { get; set; }
        public Nullable<int> NextPlug { get; set; }
        public string InsertedBy { get; set; }
        public Nullable<System.DateTime> InsertedAt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<int> StartingMileage { get; set; }
    }
}
