//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UsersDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationLog
    {
        public int NotificationLogId { get; set; }
        public string Email { get; set; }
        public int CarId { get; set; }
        public string Type { get; set; }
        public Nullable<bool> IsSend { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
    }
}
